---
version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_USER="root"
      - MYSQL_DATABASE="dev"
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
...

